declare var QueryString: {};
declare var viewer: Xbim.Viewer.Viewer;
declare var model: string;
declare var span: HTMLElement;
declare var types: typeof Xbim.Viewer.ProductType;
declare var states: typeof Xbim.Viewer.State;
declare var makeWallsRed: () => void;
declare var selectAllWalls: () => void;
declare var hideWalls: () => void;
declare var resetWalls: () => void;
declare var clip: () => void;
declare var unclip: () => void;
declare var cube: Xbim.Viewer.Plugins.NavigationCube;
