# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    versionSource: 'spec'
    version: '26.x'

# - task: npmAuthenticate@0
#   displayName: Authenticate via NPM
#   inputs:
#     workingFile: $(Build.SourcesDirectory)/.npmrc

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifacts'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/dist'
    artifact: 'dist'
    publishLocation: 'pipeline'

- task: Npm@1
  displayName: 'Publish to NPM'
  inputs:
    command: 'custom'
    workingDir: 'dist'
    customCommand: 'publish --tag=beta'
    customEndpoint: 'npm @xbim organisation'
