using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ShaderPacker
{
    class Program
    {
        static void Main(string[] args)
        {
            var basePath = Environment.CurrentDirectory;
            if (args.Length > 0)
                basePath = args[0];
            var output = "xbim-shaders.js";
            if (args.Length > 1)
                output = args[1];
            var minify = false;
            if (args.Contains("-min"))
                minify = true;

            var shaders = Directory.EnumerateFiles(basePath, "*.c", SearchOption.TopDirectoryOnly).ToArray();
            if (shaders.Length == 0)
            {
                Console.WriteLine("There are no shaders in source folder.");
                Console.WriteLine("Usage:");
                Console.WriteLine("spacker [base directory] [output file] [-min]");
                Console.WriteLine("base directory: directory containing shaders in *.c files. All shader files will be packed into result file.");
                Console.WriteLine("output file: path and name of the result file. If the file exists it will be overwritten.");
                Console.WriteLine("-min : If you define -min switch result will be stripped of comments and blank characters.");
                Console.WriteLine();
                Console.WriteLine("Default values are:");
                Console.WriteLine("spacker .\\ xbim-shaders.js");
                Console.WriteLine();
                Console.ReadKey();
                return;
            }

            using (var tw = File.CreateText(Path.Combine(basePath, output)))
            {
                tw.WriteLine("/*");
                tw.WriteLine("* This file has been generated by spacker.exe utility. Do not change this file manualy as your changes");
                tw.WriteLine("* will get lost when the file is regenerated. Original content is located in *.c files.");
                tw.WriteLine("*/");

                //start object definition
                tw.WriteLine("function xShaders() {");
                tw.WriteLine("    var result = {};");

                //get content of every shader and create JS property containing code content of the shader
                for (var j = 0; j < shaders.Length; j++ )
                {
                    var shader = shaders[j];
                    var isLastShader = j == (shaders.Length - 1);
                    var shaderName = Path.GetFileNameWithoutExtension(shader);
                    shaderName = shaderName.Replace('.', '_');
                    tw.Write(String.Format("    result.{0} = {1}", shaderName, minify ? "\"" : ""));

                    var lines = File.ReadAllLines(shader);
                    for (var i = 0; i < lines.Length; i++)
                    {
                        var line = lines[i];
                        var isLast = i == (lines.Length - 1);

                        if (minify)
                        {
                            //remove comments
                            var exp = new Regex("//.*");
                            var stripLine = exp.Replace(line, "").Trim();
                            if (!String.IsNullOrEmpty(stripLine))
                                tw.Write(" " + stripLine);
                        }
                        else
                            tw.WriteLine(String.Format("\"{0} \\n \" {1}", line, isLast ? "" : "+"));

                    }
                    if (minify)
                        tw.WriteLine(String.Format("\";"));
                    else
                        tw.WriteLine(String.Format(";"));

                }

                tw.WriteLine("    return result;");
                tw.WriteLine("}");
                tw.Close();
            }
        }
    }
}
